title: Andrianony Ny Aina Ianjatina
description: Ph.D Student in Development Policy

navbar-links:
  CV: "cv"
  Publications: "publications"
  Work in Progress: "working"
  Teaching: "teaching"
  Contact: "contact"
