title: Andrianony Ny Aina Ianjatina
description: PhD Student in Development Policy | KDI School

navbar-links:
  Home: ""
  CV: "cv"
  Research: "research"
  Teaching: "teaching"
  Field Experience: "field"
